---
# This playbook deploys FreeIPA and LemonLDAP

- hosts: all
  remote_user: root
  roles:
    - ca

- hosts: ldap.example2.com
  remote_user: root
  vars_files:
    - secrets.yml
  roles:
    - ipa

- hosts: sso.example2.com
  remote_user: root
  vars_files:
    - secrets.yml
  roles:
    - lemonldap
