- name: download OW2 key
  get_url: >
    url=http://lemonldap-ng.org/_media/rpm-gpg-key-ow2
    dest=/root/rpm-gpg-key-ow2
    sha256sum=b3170d6400502baed0b3b6288d4e250da60999b0435709be50ebd380a9e4bca9
  register: ow2
  tags: sso

- name: trust OW2 key for rpms
  shell: rpm --import /root/rpm-gpg-key-ow2
  when: ow2.changed

- name: Copy LemonLDAP rpm repository
  copy: src=rpm/lemonldap-ng.repo dest=/etc/yum.repos.d/lemonldap-ng.repo

- name: Install some dependancies
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - openldap-clients
    - epel-release
    - mod_ssl

- name: Setup OpenLDAP client configuration file
  template: src={{ item }} dest=/etc/openldap/
  with_fileglob:
    - ../templates/etc/openldap/*
  tags: [ 'ldap', 'ldap-config' ]

- name: Install LemonLDAP
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - lemonldap-ng
    - lemonldap-ng-fr-doc
    - perl-LWP-Protocol-https
  tags: sso

- name: Install configuration files
  template: src={{ item }} dest=/etc/lemonldap-ng/
  with_fileglob:
    - ../templates/etc/lemonldap-ng/*
  notify:
    - restart httpd
  tags: [ 'sso', 'sso-config' ]

- name: Install LemonLDAP configuration files
  template: src={{ item }} dest=/var/lib/lemonldap-ng/conf/
  with_fileglob:
    - ../templates/var/lib/lemonldap-ng/conf/*
  notify:
    - restart httpd
  tags: [ 'sso', 'sso-config' ]

- name: Install SSO TLS certificate
  copy: >
    content="{{ item.value }}"
    dest=/etc/ssl/httpd/{{ item.key }}
    owner=apache group=apache mode=0600
  with_dict: "{{ sso.certs_and_keys }}"
  notify:
    - restart httpd
  tags: [ 'sso', 'sso-config' ]

- name: Update SSL configuration file
  copy: src={{ item }} dest=/etc/httpd/conf.d/ owner=apache group=apache mode=0644
  with_items:
    - etc/httpd/conf.d/ssl.conf
  notify:
    - restart httpd
  tags: [ 'sso', 'sso-config' ]

- name: Install Gogs reverse proxy (optional)
  template: src=etc/httpd/conf.d/gogs.conf dest=/etc/httpd/conf.d/gogs.conf
  when: sso.gogs_internal_name is defined
  notify:
    - restart httpd
  tags: [ 'sso', 'sso-config' ]
