- name: Install FreeIPA
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - openldap-clients
    - ipa-server

- name: Copy FreeIPA PEM and CA files
  copy: content="{{ item.value }}" dest=/var/lib/ipa/{{ item.key }} owner=root group=root mode=600
  with_dict: "{{ ldap.certs_and_keys }}"
  tags: [ 'ldap', 'ldap-config' ]

- name: Setup FreeIPA
  script: scripts/setup-ipa.sh
  environment: "{{ldap}}"
  args:
    creates : /var/lib/ipa/sysrestore/sysrestore.state
